import { StyleSheet } from "react-native";
import cores from "../../../utils/cores";

const estilosProdutos = StyleSheet.create({
  corFundo: {
    flex: 1,
    backgroundColor: cores.bgCream,
    paddingBottom: 10,
  },
  titulo: {
    fontFamily: "FonteBold",
    fontSize: 26,
    color: cores.brownDark,
    textAlign: "center",
    paddingTop: 16,
  },
  subtitulo: {
    fontSize: 14,
    color: cores.brownOrange,
    textAlign: "center",
    fontStyle: "italic",
    paddingBottom: 10,
  },
  lista: {
    paddingBottom: 100,
  },
  card: {
    width: "92%",
    marginVertical: 8,
    alignSelf: "center",
    borderWidth: 2,
    borderColor: cores.brownLight,
    backgroundColor: cores.white,
  },
  nomeProduto: {
    fontFamily: "FonteBold",
    color: cores.brownDark,
    fontSize: 20,
    paddingTop: 8,
    paddingBottom: 2,
    textAlign: "left",
  },
  descProduto: {
    color: cores.brownMedium,
    fontSize: 14,
    paddingBottom: 6,
  },
  precoProduto: {
    fontFamily: "FonteBold",
    color: cores.brownOrange,
    fontSize: 18,
    textAlign: "left",
    paddingBottom: 4,
  },
  imagem: {
    width: "100%",
    height: 180,
  },
  botao: {
    backgroundColor: cores.brownDark,
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  botaoSecundario: {
    backgroundColor: cores.brownOrange,
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  textoBotao: {
    fontSize: 13,
    color: cores.white,
    fontFamily: "FonteBold",
    textAlign: "center",
  },
  botaoFlutuante: {
    position: "absolute",
    right: 16,
    bottom: 20,
    backgroundColor: cores.brownOrange,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    borderWidth: 2,
    borderColor: cores.brownDark,
  },
  textoBotaoFlutuante: {
    color: cores.white,
    fontFamily: "FonteBold",
    fontSize: 14,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(59, 31, 14, 0.55)",
  },
  modal: {
    width: "88%",
    backgroundColor: cores.bgCream,
    borderWidth: 3,
    borderColor: cores.brownOrange,
    borderRadius: 14,
    padding: 18,
    alignItems: "center",
  },
  botaoFechar: {
    alignSelf: "flex-end",
  },
  imagemModal: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    marginBottom: 12,
  },
  nomeProdutoModal: {
    fontFamily: "FonteBold",
    fontSize: 22,
    color: cores.brownDark,
    textAlign: "center",
    paddingTop: 4,
  },
  precoModal: {
    fontFamily: "FonteBold",
    fontSize: 20,
    color: cores.brownOrange,
    textAlign: "center",
    paddingBottom: 8,
  },
  descProdutoModal: {
    color: cores.brownDark,
    fontSize: 14,
    paddingHorizontal: 4,
    paddingBottom: 14,
  },
  botaoPedirModal: {
    backgroundColor: cores.brownOrange,
    borderRadius: 8,
    paddingHorizontal: 24,
    paddingVertical: 10,
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  modalCarrinhoContainer: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(59, 31, 14, 0.55)",
  },
  modalCarrinho: {
    backgroundColor: cores.bgCream,
    borderTopWidth: 3,
    borderColor: cores.brownOrange,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 18,
    maxHeight: "85%",
  },
  cabecalhoCarrinho: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  tituloCarrinho: {
    fontFamily: "FonteBold",
    fontSize: 22,
    color: cores.brownDark,
  },
  carrinhoVazio: {
    textAlign: "center",
    color: cores.brownMedium,
    fontStyle: "italic",
    paddingVertical: 20,
  },
  listaCarrinho: {
    maxHeight: 240,
    marginBottom: 8,
  },
  itemCarrinho: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: cores.white,
    borderWidth: 1,
    borderColor: cores.brownLight,
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
  },
  itemInfo: {
    flex: 1,
    paddingRight: 8,
  },
  itemNome: {
    fontFamily: "FonteBold",
    fontSize: 14,
    color: cores.brownDark,
  },
  itemPreco: {
    fontSize: 12,
    color: cores.brownMedium,
    fontStyle: "italic",
  },
  itemControles: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  botaoQtd: {
    backgroundColor: cores.brownDark,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  itemQtd: {
    fontFamily: "FonteBold",
    fontSize: 14,
    color: cores.brownDark,
    minWidth: 24,
    textAlign: "center",
  },
  botaoRemover: {
    backgroundColor: cores.brownOrange2,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 6,
  },
  linhaTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderTopWidth: 2,
    borderTopColor: cores.brownLight,
    marginTop: 4,
  },
  totalRotulo: {
    fontFamily: "FonteBold",
    fontSize: 16,
    color: cores.brownDark,
  },
  totalValor: {
    fontFamily: "FonteBold",
    fontSize: 18,
    color: cores.brownOrange,
  },
  rotuloNome: {
    fontFamily: "FonteBold",
    fontSize: 14,
    color: cores.brownDark,
    marginTop: 12,
    marginBottom: 4,
  },
  inputNome: {
    fontFamily: "FonteRegular",
    fontSize: 16,
    color: cores.brownDark,
    backgroundColor: cores.bgCream2,
    borderWidth: 1,
    borderColor: cores.brownLight,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 12,
  },
  botaoFinalizar: {
    backgroundColor: cores.brownOrange,
    borderRadius: 10,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  botaoDesativado: {
    opacity: 0.5,
  },
  textoBotaoFinalizar: {
    color: cores.white,
    fontFamily: "FonteBold",
    fontSize: 16,
  },
});

export default estilosProdutos;
